### ISSUE TITLE
0.2.0 fails to build on Arch/gcc 8.2.1

### ISSUE THREAD

**Issue by Unb9rn** [OpenSC/pam_p11#14]
Hello! I am having a hard time building latest version:

```
make  all-recursive
make[1]: Entering directory '/tmp/pam_p11/pam_p11-0.2.0'
Making all in po
make[2]: Entering directory '/tmp/pam_p11/pam_p11-0.2.0/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/pam_p11/pam_p11-0.2.0/po'
Making all in src
make[2]: Entering directory '/tmp/pam_p11/pam_p11-0.2.0/src'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..       -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -Wall -Wextra -Wno-unused-parameter -Werror -MT pam_p11.lo -MD -MP -MF .deps/pam_p11.Tpo -c -o pam_p11.lo pam_p11.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -Wall -Wextra -Wno-unused-parameter -Werror -MT pam_p11.lo -MD -MP -MF .deps/pam_p11.Tpo -c pam_p11.c  -fPIC -DPIC -o .libs/pam_p11.o
pam_p11.c: In function ‘key_verify’:
pam_p11.c:593:8: error: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Werror=implicit-function-declaration]
    || !EVP_MD_CTX_cleanup(md_ctx)
        ^~~~~~~~~~~~~~~~~~
        EVP_MD_CTX_create
cc1: all warnings being treated as errors
make[2]: *** [Makefile:519: pam_p11.lo] Error 1
make[2]: Leaving directory '/tmp/pam_p11/pam_p11-0.2.0/src'
make[1]: *** [Makefile:496: all-recursive] Error 1
make[1]: Leaving directory '/tmp/pam_p11/pam_p11-0.2.0'
make: *** [Makefile:407: all] Error 2

```

**Comment by frankmorgner** [comment]
please attach your config.log

**Comment by Unb9rn** [comment]
Of course!
[config.log](https://github.com/OpenSC/pam_p11/files/3084193/config.log)

**Comment by Unb9rn** [comment]
Just in case... The problem reproduces with gcc 8.3

**Comment by frankmorgner** [comment]
I'm not quite sure what's going on. OpenSSL should have either `EVP_MD_CTX_reset` or `EVP_MD_CTX_cleanup`. `configure` checks for the former (found in newer OpenSSL versions) and uses the latter if not found. Could you check your OpenSSL headers for those functions? What's your OpenSSL version; are you using libressl?

**Comment by Unb9rn** [comment]
Running Openssl:
```
openssl version
OpenSSL 1.1.1b  26 Feb 2019
```
I have /usr/include/openssl and /usr/include/openssl-1.0/openssl locations with evp.h headers (looks like OpenSSL 1.1 breaks a lot, so if I understand everything right arch has 1.0 version too)

/usr/include/openssl has EVP_MD_CTX_reset, while /usr/include/openssl-1.0/openssl has EVP_MD_CTX_cleanup...

**Comment by Unb9rn** [comment]
I've also tried building it against OpenSSL 1.0 with 
`PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig ./configure`
Now it gets a little further but fails with:

> gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/include/openssl-1.0    -DLOCALEDIR=\"/usr/local/share/locale\" -DLIBDIR=\"/usr/local/lib\" -DTEST -g -O2 -Wall -Wextra -Wno-unused-parameter -Werror -MT test_login-test.o -MD -MP -MF .deps/test_login-test.Tpo -c -o test_login-test.o `test -f 'test.c' || echo './'`test.c
> test.c: In function ‘main’:
> test.c:58:4: error: ‘strncpy’ specified bound 32 equals destination size [-Werror=stringop-truncation]
>     strncpy(user, argv[2], sizeof user);
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> test.c:61:4: error: ‘strncpy’ specified bound 4096 equals destination size [-Werror=stringop-truncation]
>     strncpy(module, argv[1], sizeof module);
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> make[2]: *** [Makefile:526: test_login-test.o] Error 1
> make[2]: Leaving directory '/tmp/pam_p11-0.2.0/src'
> make[1]: *** [Makefile:496: all-recursive] Error 1
[config.log](https://github.com/OpenSC/pam_p11/files/3110791/config.log)
[config.log](https://github.com/OpenSC/pam_p11/files/3110794/config.log)

**Comment by frankmorgner** [comment]
The last error is already fixed in latest master.

**Comment by frankmorgner** [comment]
> Running Openssl:
> 
> ```
> openssl version
> OpenSSL 1.1.1b  26 Feb 2019
> ```
> 
> I have /usr/include/openssl and /usr/include/openssl-1.0/openssl locations with evp.h headers (looks like OpenSSL 1.1 breaks a lot, so if I understand everything right arch has 1.0 version too)
> 
> /usr/include/openssl has EVP_MD_CTX_reset, while /usr/include/openssl-1.0/openssl has EVP_MD_CTX_cleanup...

`configure.ac` tests for `EVP_MD_CTX_reset` by checking libcrypto, but not by checking the `openssl/evp.h`. Maybe your linker and compiler flags don't match when calling `./configure`..., if you have both openssl versions installed it could be possible that the configure script *accidentally* links to OpenSSL 1.0.2 instead of 1.1.1

**Comment by Unb9rn** [comment]
Any ideas how can I fix it? Some override condition?

**Comment by frankmorgner** [comment]
you could try passing the flags for OpenSSL 1.1.1 manually, i.e. `./configure OPENSSL_LIBS="-L... -lcrypto" OPENSSL_CFLAGS=-I...`

**Comment by Unb9rn** [comment]
Tried using ./configure OPENSSL_LIBS="-L/usr/lib -lcrypto" OPENSSL_CFLAGS=-I/usr/include/openssl
/usr/lib has libcrypto.so and libssl.so, /usr/include/openssl has evp.h (and all other headers)... Still make drops to the same error-(implicit-function-declaration) EVP_MD_CTX_cleanup

**Comment by frankmorgner** [comment]
I just realized that the check for `EVP_MD_CTX_reset()` is in master, but not released yet. I've successfully tested the following:
```
git clone https://github.com/openssl/openssl.git
cd openssl
git checkout OpenSSL_1_1_1-stable 
./config --prefix=$PWD/.local -g -O0
make
make install_sw
cd ..
git clone https://github.com/OpenSC/libp11
cd libp11
autoreconf -vis
./configure --prefix=$PWD/../openssl/.local/ PKG_CONFIG_PATH=$PWD/../openssl/.local/lib/pkgconfig
make install
cd ..
git clone https://github.com/OpenSC/pam_p11.git
cd pam_p11
autoreconf -vis
./configure --prefix=$PWD/../openssl/.local/ PKG_CONFIG_PATH=$PWD/../openssl/.local/lib/pkgconfig
make install
cd ..
```

**Comment by Unb9rn** [comment]
Thank you! A little indelicate question... Are there any plans to release new versions of OpenSC/pam_p11/pam_pkcs11 in any foreseeable future? I was unable to find any roadmaps or plans)

**Comment by frankmorgner** [comment]
sure, soon

**Comment by frankmorgner** [comment]
done
